// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ProcessProxy")]
[assembly: AssemblyProductAttribute("ProcessProxy")]
[assembly: AssemblyDescriptionAttribute("Prototype of a library to proxy a class that is instantiated and executed in another process")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "ProcessProxy";
        internal const System.String AssemblyProduct = "ProcessProxy";
        internal const System.String AssemblyDescription = "Prototype of a library to proxy a class that is instantiated and executed in another process";
        internal const System.String AssemblyVersion = "0.1";
        internal const System.String AssemblyFileVersion = "0.1";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
